# Dictionary mapping subjects to related fields
subject_to_fields = {
    "Mathematics": ["Statistics", "Actuarial Science", "Engineering", "Data Analysis", "Cryptography",
                    "Operations Research", "Mathematical Modelling", "Teaching", "Financial Mathematics",
                    "Computational Mathematics"],
    "Physics": ["Astrophysics", "Quantum Mechanics", "Engineering", "Nuclear Physics", "Medical Physics", "Optics",
                "Condensed Matter Physics", "Geophysics", "Particle Physics", "Acoustics"],
    "Chemistry": ["Pharmaceuticals", "Biochemistry", "Environmental Science", "Forensic Science", "Material Science",
                  "Chemical Engineering", "Analytical Chemistry", "Organic Chemistry", "Inorganic Chemistry",
                  "Physical Chemistry"],
    "Biology": ["Genetics", "Biotechnology", "Medicine", "Microbiology", "Marine Biology", "Botany", "Zoology",
                "Ecology", "Evolutionary Biology", "Bioinformatics"],
    "Computer Science": ["Software Development", "Data Science", "Cybersecurity", "Artificial Intelligence",
                         "Computer Networks", "Database Management", "Human-Computer Interaction", "Robotics",
                         "Systems Analysis", "Web Development"],
    "Economics": ["Finance", "Business Analysis", "Public Policy", "International Economics", "Development Economics",
                  "Labor Economics", "Behavioral Economics", "Environmental Economics", "Health Economics",
                  "Econometrics"],
    "History": ["Archaeology", "Anthropology", "Museology", "Historical Research", "Archival Science",
                "Cultural Resource Management", "Teaching", "Historical Preservation", "Genealogy", "Paleography"],
    "Geography": ["Urban Planning", "Environmental Science", "Geology", "Cartography", "Climatology",
                  "Geospatial Analysis", "Hydrology", "Land Surveying", "Remote Sensing", "Meteorology"],
    "Literature": ["Creative Writing", "Journalism", "Publishing", "Editing", "Teaching", "Linguistics",
                   "Literary Criticism", "Translation", "Screenwriting", "Copywriting"]
}

recommendations = {
            "Statistics": ["Statistician", "Data Analyst"],
            "Actuarial Science": ["Actuary"],
            "Engineering": ["Engineer", "Project Manager"],
            "Data Analysis": ["Data Analyst", "Business Intelligence Analyst"],
            "Cryptography": ["Cryptographer", "Security Analyst"],
            "Operations Research": ["Operations Research Analyst"],
            "Mathematical Modelling": ["Research Scientist", "Quantitative Analyst"],
            "Financial Mathematics": ["Quantitative Analyst", "Risk Analyst"],
            "Computational Mathematics": ["Computational Scientist", "Software Developer"],
            "Astrophysics": ["Astrophysicist", "Research Scientist"],
            "Quantum Mechanics": ["Physicist", "Research Scientist"],
            "Nuclear Physics": ["Nuclear Physicist", "Medical Physicist"],
            "Medical Physics": ["Medical Physicist", "Radiation Therapist"],
            "Optics": ["Optical Engineer", "Photonics Technician"],
            "Condensed Matter Physics": ["Condensed Matter Physicist", "Materials Scientist"],
            "Geophysics": ["Geophysicist", "Seismologist"],
            "Particle Physics": ["Particle Physicist", "Research Scientist"],
            "Acoustics": ["Acoustical Engineer", "Sound Engineer"],
            "Pharmaceuticals": ["Pharmacist", "Research Scientist"],
            "Biochemistry": ["Biochemist", "Lab Technician"],
            "Forensic Science": ["Forensic Scientist", "Crime Lab Analyst"],
            "Material Science": ["Materials Scientist", "Research Scientist"],
            "Chemical Engineering": ["Chemical Engineer", "Process Engineer"],
            "Analytical Chemistry": ["Analytical Chemist", "Lab Technician"],
            "Organic Chemistry": ["Organic Chemist", "Research Scientist"],
            "Inorganic Chemistry": ["Inorganic Chemist", "Research Scientist"],
            "Physical Chemistry": ["Physical Chemist", "Research Scientist"],
            "Genetics": ["Geneticist", "Research Scientist"],
            "Biotechnology": ["Biotechnologist", "Lab Technician"],
            "Medicine": ["Doctor", "Surgeon"],
            "Microbiology": ["Microbiologist", "Research Scientist"],
            "Marine Biology": ["Marine Biologist", "Research Scientist"],
            "Botany": ["Botanist", "Plant Scientist"],
            "Zoology": ["Zoologist", "Wildlife Biologist"],
            "Ecology": ["Ecologist", "Conservation Scientist"],
            "Evolutionary Biology": ["Evolutionary Biologist", "Research Scientist"],
            "Bioinformatics": ["Bioinformatician", "Computational Biologist"],
            "Software Development": ["Software Developer", "App Developer"],
            "Data Science": ["Data Scientist", "Machine Learning Engineer"],
            "Cybersecurity": ["Cybersecurity Analyst", "Penetration Tester"],
            "Artificial Intelligence": ["AI Engineer", "Machine Learning Engineer"],
            "Computer Networks": ["Network Engineer", "System Administrator"],
            "Database Management": ["Database Administrator", "Data Architect"],
            "Human-Computer Interaction": ["UX Designer", "HCI Researcher"],
            "Robotics": ["Robotics Engineer", "Automation Engineer"],
            "Systems Analysis": ["Systems Analyst", "IT Consultant"],
            "Web Development": ["Web Developer", "Front-End Developer"],
            "Finance": ["Financial Analyst", "Investment Banker"],
            "Business Analysis": ["Business Analyst", "Consultant"],
            "Public Policy": ["Policy Analyst", "Government Advisor"],
            "International Economics": ["International Economist", "Trade Analyst"],
            "Development Economics": ["Development Economist", "Project Manager"],
            "Labor Economics": ["Labor Economist", "HR Analyst"],
            "Behavioral Economics": ["Behavioral Economist", "Market Researcher"],
            "Environmental Economics": ["Environmental Economist", "Sustainability Analyst"],
            "Health Economics": ["Health Economist", "Healthcare Consultant"],
            "Econometrics": ["Econometrician", "Data Analyst"],
            "Archaeology": ["Archaeologist", "Museum Curator"],
            "Anthropology": ["Anthropologist", "Researcher"],
            "Museology": ["Museum Curator", "Archivist"],
            "Historical Research": ["Historian", "Researcher"],
            "Archival Science": ["Archivist", "Records Manager"],
            "Cultural Resource Management": ["CRM Specialist", "Heritage Manager"],
            "Historical Preservation": ["Historic Preservationist", "Conservation Specialist"],
            "Genealogy": ["Genealogist", "Family Historian"],
            "Paleography": ["Paleographer", "Historical Researcher"],
            "Urban Planning": ["Urban Planner", "Environmental Consultant"],
            "Environmental Science": ["Environmental Scientist", "Conservationist"],
            "Geology": ["Geologist", "Mining Engineer"],
            "Cartography": ["Cartographer", "GIS Specialist"],
            "Climatology": ["Climatologist", "Weather Analyst"],
            "Geospatial Analysis": ["Geospatial Analyst", "GIS Technician"],
            "Hydrology": ["Hydrologist", "Water Resources Specialist"],
            "Land Surveying": ["Land Surveyor", "Geomatics Engineer"],
            "Remote Sensing": ["Remote Sensing Scientist", "GIS Analyst"],
            "Meteorology": ["Meteorologist", "Weather Forecaster"],
            "Creative Writing": ["Writer", "Author"],
            "Journalism": ["Journalist", "Editor"],
            "Publishing": ["Publisher", "Editor"],
            "Editing": ["Editor", "Proofreader"],
            "Teaching": ["Literature Teacher", "University Professor"],
            "Linguistics": ["Linguist", "Language Researcher"],
            "Literary Criticism": ["Literary Critic", "Researcher"],
            "Translation": ["Translator", "Interpreter"],
            "Screenwriting": ["Screenwriter", "Scriptwriter"],
            "Copywriting": ["Copywriter", "Content Writer"]
        }